name: ⚙️ Create New Release

on:
  push:
    branches:
      - release/*

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Extract version from branch name
        id: get_version
        run: |
          branch_name=${GITHUB_REF#refs/heads/release/}
          echo "Extracted version: $branch_name"
          echo "new_version=$branch_name" >> $GITHUB_ENV

      - name: Create new Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ steps.get_version.outputs.new_version }}
          git push https://x-access-token:${{ secrets.PAT }}@github.com/iamspydey/flutter_ignitr_multi_flavors_test.git ${{ steps.get_version.outputs.new_version }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh release create ${{ steps.get_version.outputs.new_version }} --title "Release ${{ steps.get_version.outputs.new_version }}" --notes "See the full changelog in [CHANGELOG.md](./CHANGELOG.md)."

      - name: Create Zip For Each Flavor
        run: |
          zip -r api-getx.zip api-getx/
          zip -r api-getx-stubs.zip api-getx-stubs/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PAT }}
          files: |
            api-getx.zip
            api-getx-stubs.zip
